title: Summer Learning
author: Zeynep Erol
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is blog about learning process of summer. It is tracking it.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
